<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyChoThueBangDia" Class="QuanLyChoThueBangDiaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-GE7NB3T\SQLEXPRESS;Initial Catalog=QuanLyChoThueBangDia;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="QuanLyChoThueBangDiaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dias" Member="Dias">
    <Type Name="Dia">
      <Column Name="MaDia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuongDia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangThue" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangDia" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IDKhachHang" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="IDTuaDe" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="IDLoaiDia" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHangs" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiDias" Member="LoaiDias">
    <Type Name="LoaiDia">
      <Column Name="MaLoai" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianChoPhepThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaThue" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Logins" Member="Logins">
    <Type Name="Login">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NhatKyThueDia" Member="NhatKyThueDias">
    <Type Name="NhatKyThueDia">
      <Column Name="NgayChoThue" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaTua" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="MaDia" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuongThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TienDatCoc" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PhiTreHen" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NgayTraDia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TuaDes" Member="TuaDes">
    <Type Name="TuaDe">
      <Column Name="MaTuaDe" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiDungTuaDe" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>