#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyChoThueBangDia")]
	public partial class QuanLyChoThueBangDiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDia(Dia instance);
    partial void UpdateDia(Dia instance);
    partial void DeleteDia(Dia instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiDia(LoaiDia instance);
    partial void UpdateLoaiDia(LoaiDia instance);
    partial void DeleteLoaiDia(LoaiDia instance);
    partial void InsertLogin(Login instance);
    partial void UpdateLogin(Login instance);
    partial void DeleteLogin(Login instance);
    partial void InsertNhatKyThueDia(NhatKyThueDia instance);
    partial void UpdateNhatKyThueDia(NhatKyThueDia instance);
    partial void DeleteNhatKyThueDia(NhatKyThueDia instance);
    partial void InsertTuaDe(TuaDe instance);
    partial void UpdateTuaDe(TuaDe instance);
    partial void DeleteTuaDe(TuaDe instance);
    #endregion
		
		public QuanLyChoThueBangDiaDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.QuanLyChoThueBangDiaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyChoThueBangDiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyChoThueBangDiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyChoThueBangDiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyChoThueBangDiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dia> Dias
		{
			get
			{
				return this.GetTable<Dia>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiDia> LoaiDias
		{
			get
			{
				return this.GetTable<LoaiDia>();
			}
		}
		
		public System.Data.Linq.Table<Login> Logins
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
		
		public System.Data.Linq.Table<NhatKyThueDia> NhatKyThueDias
		{
			get
			{
				return this.GetTable<NhatKyThueDia>();
			}
		}
		
		public System.Data.Linq.Table<TuaDe> TuaDes
		{
			get
			{
				return this.GetTable<TuaDe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dias")]
	public partial class Dia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDia;
		
		private int _SoLuongDia;
		
		private string _TinhTrangThue;
		
		private string _TinhTrangDia;
		
		private string _IDKhachHang;
		
		private string _IDTuaDe;
		
		private string _IDLoaiDia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaChanging(int value);
    partial void OnMaDiaChanged();
    partial void OnSoLuongDiaChanging(int value);
    partial void OnSoLuongDiaChanged();
    partial void OnTinhTrangThueChanging(string value);
    partial void OnTinhTrangThueChanged();
    partial void OnTinhTrangDiaChanging(string value);
    partial void OnTinhTrangDiaChanged();
    partial void OnIDKhachHangChanging(string value);
    partial void OnIDKhachHangChanged();
    partial void OnIDTuaDeChanging(string value);
    partial void OnIDTuaDeChanged();
    partial void OnIDLoaiDiaChanging(string value);
    partial void OnIDLoaiDiaChanged();
    #endregion
		
		public Dia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDia", DbType="Int NOT NULL")]
		public int SoLuongDia
		{
			get
			{
				return this._SoLuongDia;
			}
			set
			{
				if ((this._SoLuongDia != value))
				{
					this.OnSoLuongDiaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDia = value;
					this.SendPropertyChanged("SoLuongDia");
					this.OnSoLuongDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangThue", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TinhTrangThue
		{
			get
			{
				return this._TinhTrangThue;
			}
			set
			{
				if ((this._TinhTrangThue != value))
				{
					this.OnTinhTrangThueChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangThue = value;
					this.SendPropertyChanged("TinhTrangThue");
					this.OnTinhTrangThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangDia", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TinhTrangDia
		{
			get
			{
				return this._TinhTrangDia;
			}
			set
			{
				if ((this._TinhTrangDia != value))
				{
					this.OnTinhTrangDiaChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangDia = value;
					this.SendPropertyChanged("TinhTrangDia");
					this.OnTinhTrangDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKhachHang", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string IDKhachHang
		{
			get
			{
				return this._IDKhachHang;
			}
			set
			{
				if ((this._IDKhachHang != value))
				{
					this.OnIDKhachHangChanging(value);
					this.SendPropertyChanging();
					this._IDKhachHang = value;
					this.SendPropertyChanged("IDKhachHang");
					this.OnIDKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTuaDe", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string IDTuaDe
		{
			get
			{
				return this._IDTuaDe;
			}
			set
			{
				if ((this._IDTuaDe != value))
				{
					this.OnIDTuaDeChanging(value);
					this.SendPropertyChanging();
					this._IDTuaDe = value;
					this.SendPropertyChanged("IDTuaDe");
					this.OnIDTuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLoaiDia", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string IDLoaiDia
		{
			get
			{
				return this._IDLoaiDia;
			}
			set
			{
				if ((this._IDLoaiDia != value))
				{
					this.OnIDLoaiDiaChanging(value);
					this.SendPropertyChanging();
					this._IDLoaiDia = value;
					this.SendPropertyChanged("IDLoaiDia");
					this.OnIDLoaiDiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHangs")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _TenKhachHang;
		
		private string _SoDienThoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    #endregion
		
		public KhachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiDias")]
	public partial class LoaiDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		private int _ThoiGianChoPhepThue;
		
		private decimal _GiaThue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnThoiGianChoPhepThueChanging(int value);
    partial void OnThoiGianChoPhepThueChanged();
    partial void OnGiaThueChanging(decimal value);
    partial void OnGiaThueChanged();
    #endregion
		
		public LoaiDia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianChoPhepThue", DbType="Int NOT NULL")]
		public int ThoiGianChoPhepThue
		{
			get
			{
				return this._ThoiGianChoPhepThue;
			}
			set
			{
				if ((this._ThoiGianChoPhepThue != value))
				{
					this.OnThoiGianChoPhepThueChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianChoPhepThue = value;
					this.SendPropertyChanged("ThoiGianChoPhepThue");
					this.OnThoiGianChoPhepThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThue", DbType="Money NOT NULL")]
		public decimal GiaThue
		{
			get
			{
				return this._GiaThue;
			}
			set
			{
				if ((this._GiaThue != value))
				{
					this.OnGiaThueChanging(value);
					this.SendPropertyChanging();
					this._GiaThue = value;
					this.SendPropertyChanged("GiaThue");
					this.OnGiaThueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Logins")]
	public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserName;
		
		private string _Pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    #endregion
		
		public Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhatKyThueDia")]
	public partial class NhatKyThueDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _NgayChoThue;
		
		private string _MaTua;
		
		private string _MaDia;
		
		private string _MaKH;
		
		private int _SoLuongThue;
		
		private decimal _TienDatCoc;
		
		private System.Nullable<decimal> _PhiTreHen;
		
		private System.Nullable<System.DateTime> _NgayTraDia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNgayChoThueChanging(System.DateTime value);
    partial void OnNgayChoThueChanged();
    partial void OnMaTuaChanging(string value);
    partial void OnMaTuaChanged();
    partial void OnMaDiaChanging(string value);
    partial void OnMaDiaChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnSoLuongThueChanging(int value);
    partial void OnSoLuongThueChanged();
    partial void OnTienDatCocChanging(decimal value);
    partial void OnTienDatCocChanged();
    partial void OnPhiTreHenChanging(System.Nullable<decimal> value);
    partial void OnPhiTreHenChanged();
    partial void OnNgayTraDiaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraDiaChanged();
    #endregion
		
		public NhatKyThueDia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChoThue", DbType="DateTime NOT NULL")]
		public System.DateTime NgayChoThue
		{
			get
			{
				return this._NgayChoThue;
			}
			set
			{
				if ((this._NgayChoThue != value))
				{
					this.OnNgayChoThueChanging(value);
					this.SendPropertyChanging();
					this._NgayChoThue = value;
					this.SendPropertyChanged("NgayChoThue");
					this.OnNgayChoThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTua", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MaTua
		{
			get
			{
				return this._MaTua;
			}
			set
			{
				if ((this._MaTua != value))
				{
					this.OnMaTuaChanging(value);
					this.SendPropertyChanging();
					this._MaTua = value;
					this.SendPropertyChanged("MaTua");
					this.OnMaTuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongThue", DbType="Int NOT NULL")]
		public int SoLuongThue
		{
			get
			{
				return this._SoLuongThue;
			}
			set
			{
				if ((this._SoLuongThue != value))
				{
					this.OnSoLuongThueChanging(value);
					this.SendPropertyChanging();
					this._SoLuongThue = value;
					this.SendPropertyChanged("SoLuongThue");
					this.OnSoLuongThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDatCoc", DbType="Money NOT NULL")]
		public decimal TienDatCoc
		{
			get
			{
				return this._TienDatCoc;
			}
			set
			{
				if ((this._TienDatCoc != value))
				{
					this.OnTienDatCocChanging(value);
					this.SendPropertyChanging();
					this._TienDatCoc = value;
					this.SendPropertyChanged("TienDatCoc");
					this.OnTienDatCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiTreHen", DbType="Money")]
		public System.Nullable<decimal> PhiTreHen
		{
			get
			{
				return this._PhiTreHen;
			}
			set
			{
				if ((this._PhiTreHen != value))
				{
					this.OnPhiTreHenChanging(value);
					this.SendPropertyChanging();
					this._PhiTreHen = value;
					this.SendPropertyChanged("PhiTreHen");
					this.OnPhiTreHenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTraDia", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTraDia
		{
			get
			{
				return this._NgayTraDia;
			}
			set
			{
				if ((this._NgayTraDia != value))
				{
					this.OnNgayTraDiaChanging(value);
					this.SendPropertyChanging();
					this._NgayTraDia = value;
					this.SendPropertyChanged("NgayTraDia");
					this.OnNgayTraDiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuaDes")]
	public partial class TuaDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTuaDe;
		
		private string _NoiDungTuaDe;
		
		private string _ImageUrl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTuaDeChanging(string value);
    partial void OnMaTuaDeChanged();
    partial void OnNoiDungTuaDeChanging(string value);
    partial void OnNoiDungTuaDeChanged();
    partial void OnImageUrlChanging(string value);
    partial void OnImageUrlChanged();
    #endregion
		
		public TuaDe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTuaDe", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTuaDe
		{
			get
			{
				return this._MaTuaDe;
			}
			set
			{
				if ((this._MaTuaDe != value))
				{
					this.OnMaTuaDeChanging(value);
					this.SendPropertyChanging();
					this._MaTuaDe = value;
					this.SendPropertyChanged("MaTuaDe");
					this.OnMaTuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTuaDe", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDungTuaDe
		{
			get
			{
				return this._NoiDungTuaDe;
			}
			set
			{
				if ((this._NoiDungTuaDe != value))
				{
					this.OnNoiDungTuaDeChanging(value);
					this.SendPropertyChanging();
					this._NoiDungTuaDe = value;
					this.SendPropertyChanged("NoiDungTuaDe");
					this.OnNoiDungTuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageUrl", DbType="NVarChar(MAX)")]
		public string ImageUrl
		{
			get
			{
				return this._ImageUrl;
			}
			set
			{
				if ((this._ImageUrl != value))
				{
					this.OnImageUrlChanging(value);
					this.SendPropertyChanging();
					this._ImageUrl = value;
					this.SendPropertyChanged("ImageUrl");
					this.OnImageUrlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
